---
abstract: 'Simple TCP-based JSONRPC client/server'
author:
  - 'Daisuke Murase <typester@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::TCP: 0.11
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-JSONRPC-Lite
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  JSON::XS: 0
requires:
  Any::Moose: 0
  AnyEvent: 5.12
  JSON: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/typester/anyevent-jsonrpc-lite-perl.git
version: 0.11002
